# Generated by Django 3.0.8 on 2020-07-16 21:46

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlocoSaidaModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Participante', models.CharField(blank=True, default='', max_length=100)),
                ('Ordem', models.CharField(blank=True, default='', max_length=3)),
                ('Tentativa', models.CharField(blank=True, default='', max_length=10)),
                ('Modelo', models.TextField(blank=True, default='', max_length=100)),
                ('SupEsq', models.TextField(blank=True, default='', max_length=100)),
                ('SupDir', models.TextField(blank=True, default='', max_length=100)),
                ('InfEsq', models.TextField(blank=True, default='', max_length=100)),
                ('InfDir', models.TextField(blank=True, default='', max_length=100)),
                ('Reforco', models.TextField(blank=True, default='', max_length=3)),
                ('Correta', models.TextField(blank=True, default='', max_length=3)),
                ('Escolheu', models.TextField(blank=True, default='', max_length=3)),
                ('Acertou', models.TextField(blank=True, default='', max_length=3)),
                ('RespVerb', models.TextField(blank=True, default='', max_length=100)),
                ('TempoInic', models.TextField(blank=True, default='', max_length=20)),
                ('TempoFin', models.TextField(blank=True, default='', max_length=20)),
                ('Sessao', models.CharField(blank=True, default='', max_length=3)),
                ('Dia', models.CharField(blank=True, default='', max_length=20)),
                ('Corretas', models.CharField(blank=True, default='0', max_length=3)),
                ('Porcentagem', models.CharField(blank=True, default='0', max_length=3)),
                ('Procedimento', models.CharField(blank=True, default='1', max_length=40)),
                ('NomeBloco', models.TextField(blank=True, default='', max_length=50)),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Cond1Bloco01Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Ordem', models.CharField(blank=True, default='', max_length=3)),
                ('Tentativa', models.CharField(blank=True, default='', max_length=10)),
                ('Modelo', models.TextField(blank=True, default='', max_length=100)),
                ('SupEsq', models.TextField(blank=True, default='', max_length=100)),
                ('SupDir', models.TextField(blank=True, default='', max_length=100)),
                ('InfEsq', models.TextField(blank=True, default='', max_length=100)),
                ('InfDir', models.TextField(blank=True, default='', max_length=100)),
                ('Reforco', models.TextField(blank=True, default='', max_length=3)),
                ('Correta', models.TextField(blank=True, default='', max_length=3)),
                ('NomeBloco', models.TextField(blank=True, default='', max_length=50)),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
