# Generated by Django 3.0.8 on 2020-07-18 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MtsApp', '0002_cond1bloco01model_procedimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blocosaidamodel',
            old_name='TempoFin',
            new_name='Horario',
        ),
        migrations.RemoveField(
            model_name='blocosaidamodel',
            name='TempoInic',
        ),
    ]
