# Generated by Django 3.0.8 on 2020-07-27 01:33

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('MtsApp', '0003_auto_20200718_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cond1Bloco02Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NomeBloco', models.TextField(blank=True, default='', max_length=50)),
                ('Ordem', models.CharField(blank=True, default='', max_length=3)),
                ('Tentativa', models.CharField(blank=True, default='', max_length=10)),
                ('Modelo', models.TextField(blank=True, default='', max_length=100)),
                ('SupEsq', models.TextField(blank=True, default='', max_length=100)),
                ('SupDir', models.TextField(blank=True, default='', max_length=100)),
                ('InfEsq', models.TextField(blank=True, default='', max_length=100)),
                ('InfDir', models.TextField(blank=True, default='', max_length=100)),
                ('Reforco', models.TextField(blank=True, default='', max_length=3)),
                ('Correta', models.TextField(blank=True, default='', max_length=3)),
                ('Procedimento', models.TextField(blank=True, default='', max_length=50)),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Cond1Bloco03Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NomeBloco', models.TextField(blank=True, default='', max_length=50)),
                ('Ordem', models.CharField(blank=True, default='', max_length=3)),
                ('Tentativa', models.CharField(blank=True, default='', max_length=10)),
                ('Modelo', models.TextField(blank=True, default='', max_length=100)),
                ('SupEsq', models.TextField(blank=True, default='', max_length=100)),
                ('SupDir', models.TextField(blank=True, default='', max_length=100)),
                ('InfEsq', models.TextField(blank=True, default='', max_length=100)),
                ('InfDir', models.TextField(blank=True, default='', max_length=100)),
                ('Reforco', models.TextField(blank=True, default='', max_length=3)),
                ('Correta', models.TextField(blank=True, default='', max_length=3)),
                ('Procedimento', models.TextField(blank=True, default='', max_length=50)),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Cond1Bloco04Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NomeBloco', models.TextField(blank=True, default='', max_length=50)),
                ('Ordem', models.CharField(blank=True, default='', max_length=3)),
                ('Tentativa', models.CharField(blank=True, default='', max_length=10)),
                ('Modelo', models.TextField(blank=True, default='', max_length=100)),
                ('SupEsq', models.TextField(blank=True, default='', max_length=100)),
                ('SupDir', models.TextField(blank=True, default='', max_length=100)),
                ('InfEsq', models.TextField(blank=True, default='', max_length=100)),
                ('InfDir', models.TextField(blank=True, default='', max_length=100)),
                ('Reforco', models.TextField(blank=True, default='', max_length=3)),
                ('Correta', models.TextField(blank=True, default='', max_length=3)),
                ('Procedimento', models.TextField(blank=True, default='', max_length=50)),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Cond1Bloco05Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NomeBloco', models.TextField(blank=True, default='', max_length=50)),
                ('Ordem', models.CharField(blank=True, default='', max_length=3)),
                ('Tentativa', models.CharField(blank=True, default='', max_length=10)),
                ('Modelo', models.TextField(blank=True, default='', max_length=100)),
                ('SupEsq', models.TextField(blank=True, default='', max_length=100)),
                ('SupDir', models.TextField(blank=True, default='', max_length=100)),
                ('InfEsq', models.TextField(blank=True, default='', max_length=100)),
                ('InfDir', models.TextField(blank=True, default='', max_length=100)),
                ('Reforco', models.TextField(blank=True, default='', max_length=3)),
                ('Correta', models.TextField(blank=True, default='', max_length=3)),
                ('Procedimento', models.TextField(blank=True, default='', max_length=50)),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Cond1Bloco06Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NomeBloco', models.TextField(blank=True, default='', max_length=50)),
                ('Ordem', models.CharField(blank=True, default='', max_length=3)),
                ('Tentativa', models.CharField(blank=True, default='', max_length=10)),
                ('Modelo', models.TextField(blank=True, default='', max_length=100)),
                ('SupEsq', models.TextField(blank=True, default='', max_length=100)),
                ('SupDir', models.TextField(blank=True, default='', max_length=100)),
                ('InfEsq', models.TextField(blank=True, default='', max_length=100)),
                ('InfDir', models.TextField(blank=True, default='', max_length=100)),
                ('Reforco', models.TextField(blank=True, default='', max_length=3)),
                ('Correta', models.TextField(blank=True, default='', max_length=3)),
                ('Procedimento', models.TextField(blank=True, default='', max_length=50)),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Cond1Bloco07Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NomeBloco', models.TextField(blank=True, default='', max_length=50)),
                ('Ordem', models.CharField(blank=True, default='', max_length=3)),
                ('Tentativa', models.CharField(blank=True, default='', max_length=10)),
                ('Modelo', models.TextField(blank=True, default='', max_length=100)),
                ('SupEsq', models.TextField(blank=True, default='', max_length=100)),
                ('SupDir', models.TextField(blank=True, default='', max_length=100)),
                ('InfEsq', models.TextField(blank=True, default='', max_length=100)),
                ('InfDir', models.TextField(blank=True, default='', max_length=100)),
                ('Reforco', models.TextField(blank=True, default='', max_length=3)),
                ('Correta', models.TextField(blank=True, default='', max_length=3)),
                ('Procedimento', models.TextField(blank=True, default='', max_length=50)),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Cond1Bloco08Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NomeBloco', models.TextField(blank=True, default='', max_length=50)),
                ('Ordem', models.CharField(blank=True, default='', max_length=3)),
                ('Tentativa', models.CharField(blank=True, default='', max_length=10)),
                ('Modelo', models.TextField(blank=True, default='', max_length=100)),
                ('SupEsq', models.TextField(blank=True, default='', max_length=100)),
                ('SupDir', models.TextField(blank=True, default='', max_length=100)),
                ('InfEsq', models.TextField(blank=True, default='', max_length=100)),
                ('InfDir', models.TextField(blank=True, default='', max_length=100)),
                ('Reforco', models.TextField(blank=True, default='', max_length=3)),
                ('Correta', models.TextField(blank=True, default='', max_length=3)),
                ('Procedimento', models.TextField(blank=True, default='', max_length=50)),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Cond1Bloco09Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NomeBloco', models.TextField(blank=True, default='', max_length=50)),
                ('Ordem', models.CharField(blank=True, default='', max_length=3)),
                ('Tentativa', models.CharField(blank=True, default='', max_length=10)),
                ('Modelo', models.TextField(blank=True, default='', max_length=100)),
                ('SupEsq', models.TextField(blank=True, default='', max_length=100)),
                ('SupDir', models.TextField(blank=True, default='', max_length=100)),
                ('InfEsq', models.TextField(blank=True, default='', max_length=100)),
                ('InfDir', models.TextField(blank=True, default='', max_length=100)),
                ('Reforco', models.TextField(blank=True, default='', max_length=3)),
                ('Correta', models.TextField(blank=True, default='', max_length=3)),
                ('Procedimento', models.TextField(blank=True, default='', max_length=50)),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Cond1Bloco10Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NomeBloco', models.TextField(blank=True, default='', max_length=50)),
                ('Ordem', models.CharField(blank=True, default='', max_length=3)),
                ('Tentativa', models.CharField(blank=True, default='', max_length=10)),
                ('Modelo', models.TextField(blank=True, default='', max_length=100)),
                ('SupEsq', models.TextField(blank=True, default='', max_length=100)),
                ('SupDir', models.TextField(blank=True, default='', max_length=100)),
                ('InfEsq', models.TextField(blank=True, default='', max_length=100)),
                ('InfDir', models.TextField(blank=True, default='', max_length=100)),
                ('Reforco', models.TextField(blank=True, default='', max_length=3)),
                ('Correta', models.TextField(blank=True, default='', max_length=3)),
                ('Procedimento', models.TextField(blank=True, default='', max_length=50)),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Cond1Bloco11Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NomeBloco', models.TextField(blank=True, default='', max_length=50)),
                ('Ordem', models.CharField(blank=True, default='', max_length=3)),
                ('Tentativa', models.CharField(blank=True, default='', max_length=10)),
                ('Modelo', models.TextField(blank=True, default='', max_length=100)),
                ('SupEsq', models.TextField(blank=True, default='', max_length=100)),
                ('SupDir', models.TextField(blank=True, default='', max_length=100)),
                ('InfEsq', models.TextField(blank=True, default='', max_length=100)),
                ('InfDir', models.TextField(blank=True, default='', max_length=100)),
                ('Reforco', models.TextField(blank=True, default='', max_length=3)),
                ('Correta', models.TextField(blank=True, default='', max_length=3)),
                ('Procedimento', models.TextField(blank=True, default='', max_length=50)),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
