# Generated by Django 3.0.8 on 2020-07-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MtsApp', '0005_cond2bloco01model_cond2bloco02model_cond2bloco03model_cond2bloco04model_cond2bloco05model_cond2bloco'),
    ]

    operations = [
        migrations.AddField(
            model_name='cond1bloco01model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cond1bloco02model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cond1bloco03model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cond1bloco04model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cond1bloco05model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cond1bloco06model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cond1bloco07model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cond1bloco08model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cond1bloco09model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cond1bloco10model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cond1bloco11model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cond2bloco01model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cond2bloco02model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cond2bloco03model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cond2bloco04model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cond2bloco05model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cond2bloco06model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cond2bloco07model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cond2bloco08model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cond2bloco09model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cond2bloco10model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cond2bloco11model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cond2bloco12model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cond2bloco13model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cond2bloco14model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cond2bloco15model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cond2bloco16model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cond2bloco17model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cond2bloco18model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cond2bloco19model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cond2bloco20model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cond2bloco21model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cond2bloco22model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cond2bloco23model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cond2bloco24model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cond2bloco25model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cond2bloco26model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cond2bloco27model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cond2bloco28model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cond2bloco29model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cond2bloco30model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cond2bloco31model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cond2bloco32model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cond2bloco33model',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
