# Generated by Django 3.0.8 on 2020-07-29 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MtsApp', '0006_auto_20200729_1716'),
    ]

    operations = [
    ]
