# Generated by Django 3.0.8 on 2020-07-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MtsApp', '0008_auto_20200729_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocosaidamodel',
            name='TipoTentativa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
