# Generated by Django 3.0.8 on 2020-07-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MtsApp', '0009_blocosaidamodel_tipotentativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocosaidamodel',
            name='ErroTipo',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
