# Generated by Django 3.0.8 on 2020-08-01 01:54

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('MtsApp', '0011_auto_20200731_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodosOsBlocos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NoBloco', models.CharField(blank=True, default='', max_length=3)),
                ('NomeBloco', models.TextField(blank=True, default='', max_length=50)),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
