# Generated by Django 3.0.8 on 2020-08-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MtsApp', '0012_todososblocos'),
    ]

    operations = [
        migrations.AddField(
            model_name='todososblocos',
            name='CriterioNao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='todososblocos',
            name='CriterioSim',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='todososblocos',
            name='NoBloco',
            field=models.IntegerField(default=0),
        ),
    ]
